name: Continuous Integration

on: [push]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Backend Dependencies
      run: cd api && npm install

    - name: Run Backend Unit Tests
      run: |
        cd api
        npm test


  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Frontend Dependencies
      run: cd frontend && npm install

    
    - name: Cypress install
      uses: cypress-io/github-action@v6

    - name: Run Frontend E2E Tests
      uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: edge
      # run: cd frontend && npm run cypress:run
