name: Continuous Integration

on: [push]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Backend Dependencies
      run: cd api && npm install

    - name: Run Backend Unit Tests
      run: cd api && npm test

  frontend-tests:
    needs: backend-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Frontend Dependencies
      run: cd frontend && npm install

    - name: Run Frontend E2E Tests
      run: cd frontend && npm run cy:run
